#!/usr/bin/env bash

stop() {
    echo ""
    echo "Gracefully shutting down daemons..."
    logger -p local1.notice "LFS manager: stopping all daemons";
    # try to gracefully shutdown all daemons
    /etc/init.d/cpanel_daemons/acl.sh stop
    /etc/init.d/cpanel_daemons/auth.sh stop
    /etc/init.d/cpanel_daemons/cron.sh stop
    /etc/init.d/cpanel_daemons/mount.sh stop
    /etc/init.d/cpanel_daemons/music.sh stop
    /etc/init.d/cpanel_daemons/proc.sh stop
    /etc/init.d/cpanel_daemons/usr.sh stop
    # wait 1 second and if there is some daemon still up cleanse it all
    sleep 1
    echo "Killing hung up daemons..."
    pkill -f "bash /web_server/daemons/"
    # remove all fifos
    echo "Removing fifos..."
    rm -rf /web_server/fifos/*
    echo "All cpanel services stopped!!"
    echo ""
    logger -p local1.notice "LFS manager: all daemons stopped";

}


start() {
echo ""
    echo "Starting all cpanel services..."
    logger -p local1.notice "LFS manager: starting all daemons";
    /etc/init.d/cpanel_daemons/acl.sh start
    /etc/init.d/cpanel_daemons/auth.sh start
    /etc/init.d/cpanel_daemons/cron.sh start
    /etc/init.d/cpanel_daemons/mount.sh start
    /etc/init.d/cpanel_daemons/music.sh start
    /etc/init.d/cpanel_daemons/proc.sh start
    /etc/init.d/cpanel_daemons/usr.sh start
    echo "All services started!!"
    echo ""
    logger -p local1.notice "LFS manager: all daemons running";
}



case $1 in

    'start')
        start
        ;;

    'stop')
        stop
        ;;

    'restart')
        echo "Restarting all cpanel services..."
        logger -p local1.notice "LFS manager: restarting all daemons";
        echo ""
        stop
        start
        echo ""
        ;;
    *)
        echo "Invalid option $1. Usage: lfs [start|stop|restart]"
        ;;
esac