#!/usr/bin/env bash

stop() {
    echo ""
    echo "Gracefully shutting down daemons..."
    # try to gracefully shutdown all daemons
    /etc/init.d/cpanel_daemons/acl.sh stop
    /etc/init.d/cpanel_daemons/auth.sh stop
    /etc/init.d/cpanel_daemons/cron.sh stop
    /etc/init.d/cpanel_daemons/proc.sh stop
    /etc/init.d/cpanel_daemons/usr.sh stop
    # wait 1 second and if there is some daemon still up cleanse it all
    sleep 1
    echo "Killing hung up daemons..."
    pkill '/etc/init.d/cpanel_daemons'
    # remove all fifos
    echo "Removing fifos..."
    rm -rf /web_server/fifos/*
    echo "All cpanel services stopped!!"
    echo ""

}


start() {
echo ""
    echo "Starting all cpanel services..."
    /etc/init.d/cpanel_daemons/acl.sh start
    /etc/init.d/cpanel_daemons/auth.sh start
    /etc/init.d/cpanel_daemons/cron.sh start
    /etc/init.d/cpanel_daemons/proc.sh start
    /etc/init.d/cpanel_daemons/usr.sh start
    echo "All services started!!"
    echo ""

}



case $1 in

    'start')
        start
        ;;

    'stop')
        stop
        ;;

    'restart')
        echo "Restarting all cpanel services..."
        echo ""
        stop
        start
        echo ""
        ;;
    *)
        echo "Invalid option $1. Usage: lfs [start|stop|restart]"
        ;;
esac